# Generated by Django 2.2 on 2021-05-28 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('nro_direccion', models.IntegerField(blank=True, null=True)),
                ('comuna', models.IntegerField(blank=True, choices=[(1, 'Providencia'), (2, 'San Bernardo'), (3, 'La Serena'), (4, 'Temuco')], default=1, null=True)),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['comuna'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.IntegerField(choices=[(1, 'Kinesiología'), (2, 'Fonoaudiología'), (3, 'General')], default=3)),
                ('dia_reservado', models.DateTimeField()),
                ('sucursal', models.IntegerField(blank=True, choices=[(1, 'Providencia'), (2, 'San Bernardo'), (3, 'La Serena'), (4, 'Temuco')], default=1, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['sucursal'],
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_especialista', models.CharField(max_length=20)),
                ('apellido_especialista', models.CharField(max_length=20)),
                ('box', models.CharField(max_length=10)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Reserva')),
            ],
            options={
                'verbose_name': 'Atencion',
                'verbose_name_plural': 'Atenciones',
                'ordering': ['reserva_id'],
            },
        ),
    ]
