# Generated by Django 3.2.3 on 2021-06-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atencion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='box',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
    ]
