# Generated by Django 3.2.4 on 2021-07-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210708_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='etapa',
            field=models.IntegerField(blank=True, choices=[(1, 'Primera'), (2, 'Segunda'), (3, 'Tercera')], default=None, null=True, verbose_name='Etapa'),
        ),
    ]
