# Generated by Django 3.2.3 on 2021-06-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210604_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atencion',
            options={'ordering': ['reserva_id'], 'verbose_name': 'Atencion', 'verbose_name_plural': 'Atenciones'},
        ),
        migrations.AlterModelOptions(
            name='box',
            options={'ordering': ['estado'], 'verbose_name': 'Box', 'verbose_name_plural': 'Boxes'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['sucursal'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
    ]
